<?php
namespace app\material;

return
    '{
        "domain":"http://shop2.dxdodoca009.com",
        "api":[
            {
                "name":"点击签到",
                "method":"get",
                "route":"/signin/signin.json"
            },
            {
                "name":"轮播图（废弃）",
                "method":"get",
                "route":"/signin/lunbo.json"
            },
            {
                "name":"日历（废弃）",
                "method":"get",
                "route":"/signin/calendar.json"
            },
            {
                "name":"签到入口",
                "method":"get",
                "route":"/signin/entrance/3.json"
            },
            {
                "name":"我的奖励",
                "method":"get",
                "route":"/signin/myreward.json"
            },
            {
                "name":"获取商品信息",
                "method":"post",
                "route":"/signin/postgoodsinfo.json",
                "args":
                {
                    "order_id":"230"
                }
            },
            {
                "name":"领取奖品",
                "method":"post",
                "route":"/signin/postreceivegoods.json",
                "args":
                {
                    "order_id":"230",
                    "get_name":"test",
                    "address":"ttt",
                    "mobile":"18000000000"
                }
            },
            {
                "name":"签到状态（废弃）",
                "method":"get",
                "route":"/signin/signinstatus.json"
            },
            {
                "name":"分享信息",
                "method":"get",
                "route":"/signin/share.json"
            },
            {
                "name":"签到页面",
                "method":"get",
                "route":"/signin/signpage.json"
            }
        ]
    }';
?>