<?php
namespace app\material;

return
'{
    "domain":"http://shop1.dxdodoca009.com",
    "api":[
        {
            "name":"判断是否已绑定",
            "method":"get",
            "route":"/appbindphone/has_bind.json"
        },
        {
            "name":"发短信",
            "method":"post",
            "route":"/appbindphone/send_message.json",
            "args":
            {
                "type":"2",
                "mobile":"18001981881"
            }
        },
        {
            "name":"绑定手机号",
            "method":"post",
            "route":"/appbindphone/bind_phone.json",
            "args":
            {
                "type":"2",
                "mobile":"18001981881",
                "sms_str":"038848"
            }
        }
    ]
}';
?>